INSERT INTO dreamBall (charName, homePlanet, powerPoints, specialSkills, charCost, ownerID) VALUES  
('Shadow', 'Crolla V2PJ', 				10, 1, 	1, 0),
('The Old Axeman', 'Xeswuyria', 		10,	2, 	1, 0),
('The Dark Eagle', 'Regriri', 			10, 3, 	1, 0),
('Doctor Old Sword', 'Joewei', 			10, 1, 	1, 0),
('The Copper Monarch', 'Wescietera', 	10, 2, 	1, 0),
('Master Misty Devil', 'Crabalara',		10,	3,	1, 0),
('The Electric Devil', 'Nusnade',		10,	1,	1, 0),
('The Brass Hammer', 'Vuitune',			10,	2,	1, 0),
('The Brass Cricket', 'Desweon',		10,	3,	1, 0),
('Captain Nifty Crane',	'Trade 131K',	10, 1,	1, 0),
('Blitzfire',	'Despeyhines',			9,	2,	1, 0),
('The Brass Wasp',	'Xaswadus',			9,	3,	1, 0),
('Broken Wolf',	'Swuiurus',				9,	1,	1, 0),
('Quantum Commander',	'Slerth 3OS',	9,	2,	1, 0),
('The Voiceless Lion',	'Jeslade',		9,	3,	1, 0),
('Dapper Smasher',	'Maogawa',			9,	1,	1, 0),
('Macho Spirit',	'Styria 494S',		9,	2,	1, 0),
('Iron Assassin',	'Slonoe 2X',		9,	3,	1, 0),
('Spectacular Swallow',	'Naenerth',		9,	1,	1, 0),
('Moonshadow',	'Flara TYQ8',			9,	2,	1, 0),
('The Scarlet Swordsman',	'Xoytov',	8,	3,	1, 0),
('Warden Rapid Owl',	'Crars KVXS',	8,	1,	1, 0),
('The Marked Ant',	'Xialea',			8,	2,	1, 0),
('Captain Fabulous Sentinel','Crenuhiri',8,	3,	1, 0),
('Nightquake',	'Bromia Z5JF',			8,	1,	1, 0),
('The Ice Bear',	'Dasmeon',			8,	2,	1, 0),
('The Defiant Katana',	'Ialia',		8,	3,	1, 0),
('Mister Hypnotic Protector','Taowei',	8,	1,	1, 0),
('Cold Daggers',	'Flakorilia',		8,	2,	1, 0),
('Warden Dapper Genius',	'Teytis',	8,	3,	1, 0),
('The Fiery Fighter',	'Bophus',		7,	1,	1, 0),
('The Fearless Slayer',	'Etroistea',	7,	2,	1, 0),
('Outrageous Nightowl',	'Huelea',		7,	3,	1, 0),
('The Gray Phoenix',	'Nasteugantu',	7,	1,	1, 0),
('Mysterious Axeman',	'Swekuvis',		7,	2,	1, 0),
('The Nuclear Crane',	'Resniehines',	7,	3,	1, 0),
('The Mammoth Termite',	'Babrov',		7,	1,	1, 0),
('Dragon Spectre',	'Strade PJ3',		7,	2,	1, 0),
('The Royal Trident',	'Gecluatania',	7,	3,	1, 0),
('The Magnificent Soldier',	'Zescurn',	7,	1,	1, 0),
('Blue Slayer',	'Skojania',				6,	2,	1, 0),
('Electric Arrow',	'Lewheinerth',		6,	3,	1, 0),
('The Misty Macaw'	,'Suetov',			6,	1,	1, 0),
('Shadow',	'Blyke EX',					6,	2,	1, 0),
('Good Killer',	'Riegantu',				6,	3,	1, 0),
('Chief Merciful Owl',	'Cloiatis',		6,	1,	1, 0),
('Doctor Voiceless Macaw',	'Fautis',	6,	2,	1, 0),
('Master Electron Spider',	'Clayeria',	6,	3,	1, 0),
('The Steel Termite',	'Poclaenia',	6,	1,	1, 0),
('Master Confident Falcon',	'Drapothea',6,	2,	1, 0),
('The Macho Owl',	'Uchoanus',			5,	3,	1, 0),
('The Ancient Prince',	'Bosmiuq',		5,	1,	1, 0),
('The Mammoth Bear',	'Huscilles',	5,	2,	1, 0),
('Master Brave Knuckles','Scerth 30A',	5,	3, 	1, 0),
('The Elegant Merlin',	'Zusnurn',		5,	1,	1, 0),
('Phantasm',	'Broth 9D',				5,	2,	1, 0),
('The Heavy Spectacle',	'Qublerth',		5,	3,	1, 0),
('Doctor Rapid Warrior',	'Tiowei',	5,	1,	1, 0),
('Doctor Ethereal Owl',	'Zaegawa',		5,	2,	1, 0),
('Professor Hot Sparrow','Flovohines',	5,	3,	1, 0),
('Huge Champion',	'Graranope',		4,	1,	1, 0),
('Crimson Elephantman',	'Whilles P22',	4,	2,	1, 0),
('Fantasia',	'Fostrogawa', 			4,	3,	1, 0),
('The Golden Veteran',	'Asnagua',		4,	1,	1, 0),
('Electron Macaw',	'Coiliv', 			4,	2,	1, 0),
('Silver Goliath',	'Oskiuyama',		4,	3,	1, 0),
('Purple Dagger',	'Grone OB7',		4,	1,	1, 0),
('Wild Tornado',	'Iepluenerth',		4,	2,	1, 0),
('The Accidental Tiger','Vastraiter',	4,	3,	1, 0),
('Moon Halo',	'Plolla ZHX',			4,	1,	1, 0),
('Titanio',	'Stolla BS6C',				3,	2, 	1, 0),
('Icicle',	'Iesloyturn', 				3,	3,	1, 0),
('Unarmed Wonder',	'Grauria',			3,	1,	1, 0),
('Confident Raccoon',	'Praater',		3,	2,	1, 0),
('Master Jolly Gorilla', 'Clade IYVD', 	3, 	3, 	1, 0),
('Misty Manta',	'Maspouphus',			3,	1,	1, 0),
('The Fantastic Gunner','Koprichi',		3,	2,	1, 0),
('The Kind Prince',	'Wasnyke',			3,	3,	1, 0),
('The Defiant Swan',	'Qotrov',		3,	1,	1, 0),
('Professor Bronze Guardian','Glewatov',3,	2,	1, 0),
('The Blue Agent',	'Xopriogantu',		2,	3,	1, 0),
('Starry Night',	'Losceyrilia',		2,	1,	1, 0),
('The Iron Seer',	'Woawei',			2,	2,	1, 0),
('Doctor Wacky Nightowl',	'Smabepra',	2,	3,	1, 0),
('Doctor Elegent Ibis',	'Stahehines',	2,	1,	1, 0),
('Mister Green Bat',	'Strawuliv',	2,	2,	1, 0),
('The Intelligent Swan',	'Gedrora',	2,	3,	1, 0),
('The Earth Siren',	'Subrone',			2,	1,	1, 0),
('Scarlet King',	'Plillon CEOY',		2,	2,	1, 0),
('Chief Cool Scepter',	'Strehurilia',	2,	3,	1, 0),
('Professor Royal Gorilla','Bragua 5',	1,	1,	1, 0),
('The Green Watcher',	'Oscov',		1,	2,	1, 0),
('Bronze Mothman',	'Smuguthea',		1,	3,	1, 0),
('The Golden Dragonfly','Lasloynope',	1,	1,	1, 0),
('The Quick Agent',	'Tuocury',			1,	2,	1, 0),
('Chief Mysterious Merlin',	'Mourilia',	1,	3,	1, 0),
('The Infamous Scimitar','Fothaunope',	1,	1,	1, 0),
('Ethereal Shepherd',	'Brukuter',		1,	2,	1, 0),
('Titanio',	'Grore 269',				1,	3,	1, 0),
('The Nuclear Duke',	'Basmion',		1,	1,	1, 0);
-- must have a ; at end of last line

